### ISSUE TITLE
unable to run, using nixos.

### ISSUE THREAD

**Issue by NestorLiao** [cab404/genix7000#7]
[I] nestor@nixos ~ [1]> nix run github:cab404/genix7000
error: unable to execute '/nix/store/5ggmnfhhib1fbk6kqx3prz5wb8pq1xr3-genix7000/bin/genix7000': Exec format error

**Comment by ChanceHarrison** [comment]
I ran into this issue trying to use this project for the first time. I see you marked it as completed/resolved a few days after opening it. Did you figure out what your problem was @NestorLiao?

Is it related to the `flake.lock` having old inputs that result in packages that don't run on my system? Or perhaps it's something else?

**Comment by cab404** [comment]
> I ran into this issue trying to use this project for the first time. I see you marked it as completed/resolved a few days after opening it. Did you figure out what your problem was [@NestorLiao](https://github.com/NestorLiao)?
> 
> Is it related to the `flake.lock` having old inputs that result in packages that don't run on my system? Or perhaps it's something else?

just do that without `flake run` — clone, update flake.lock and run `to-image.nu`
